@startuml
hide footbox
title The MarketPlace contract (v1)

actor Vendor1
actor Vendor2
participant MarketPlace <<Contract>>
actor Client

Vendor1->MarketPlace : registerVendor(name1, barcode, stockCount1)
Vendor2->MarketPlace : registerVendor(name2, barcode, stockCount2)
Client->MarketPlace : requestAsset(barcode, quantity, max_date)

alt successful case
   MarketPlace-->Vendor1 : 'barcode' is requested for a quantity 'quantity' until 'max_date'.
   Vendor1->Vendor1 : checkStock(barcode, quantity)
   MarketPlace-->Vendor2 : 'barcode' is requested for a quantity 'quantity' until 'max_date'.
   Vendor2->Vendor2 : checkStock(barcode, quantity)
   Vendor1->MarketPlace : makeOffer(barcode, price1)
   Vendor2->MarketPlace : makeOffer(barcode, price2)
   MarketPlace->MarketPlace : selectAnOffer(selection_criteria) 
   MarketPlace-->Client : The asset 'barcode' is available with price 'price2'. 
   alt acceptance of the offer
      Client->MarketPlace : acceptOffer(amount)
      MarketPlace-->Client : Payment received for the asset 'barcode'.
      MarketPlace-> Vendor2: transfer(amount)
      MarketPlace-->Client : The asset 'barcode' has been shipped with the tracking number 'trackingNo'.
   else refusal of the offer
      Client->MarketPlace : refuseOffer()
   end
else at any time
   Client->MarketPlace : cancelRequest(barcode)
end
@enduml
