@startuml
actor Vendor1
actor Vendor2
participant MarketPlace
actor Client

Vendor1->MarketPlace : registerVendor(name1, A, stockCount1)
Vendor2->MarketPlace : registerVendor(name2, A, stockCount2)
Client->MarketPlace : requestAsset(barcoe, quantity, max_date)

alt successful case
   MarketPlace-->Vendor1 : The asset 'barcode' is requested for a quantity 'quantity' until the date 'max_date'.
   MarketPlace-->Vendor2 : Asset 'barcode' is requested.
   Vendor1->MarketPlace : sendOffer(barcode, price1)
   Client->MarketPlace : requestAsset(barcode, requested_quantity, max_date)
   MarketPlace-->Vendor1 : The asset 'barcode' is requested for a quantity 'another_quantity' until 'max_date'.
   MarketPlace-->Vendor2 : Asset 'barcode' is requested.
   Vendor1->MarketPlace : sendOffer(barcode, price1)
   Vendor2->MarketPlace : sendOffer(barcode, price2)
   MarketPlace-->Client : Bidding finished for the asset 'barcode' with price 'price2'.
   alt the offer is accepted
      Client->MarketPlace : acceptOffer(amount)
      MarketPlace-->Client : Payment received for the asset 'barcode'.
      MarketPlace-> Vendor2: transfer(amount)
      MarketPlace-->Client : The asset 'barcode' has been shipped with the tracking number 'trackingNo'.
   else the offer is refused
      Client->MarketPlace : refuseOffer()
   end
else at any time
   Client->MarketPlace : cancelRequest(barcode)
end
@enduml
